on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
    
jobs:
  validate:
    name: Validate XML files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: anyone-developer/anyone-validate-xml@0.9.2
        with:
          file-extension: '.xml'
          read-path: '.'
