on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
    types: [opened, synchronize, reopened, ready_for_review]
    
jobs:
  build:
    name: Build and validate token sheets
    runs-on: ubuntu-latest
    permissions: write-all

    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout sheets
        uses: actions/checkout@v4

      - name: Run build script
        run: |
          mkdir built
          python -m scripts.build

      - name: Save to built branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: built
          FOLDER: built
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build {sha}: {msg}"
